spring:
  application:
    name: analysis-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8091

eureka:
  client:
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

